In [101]:
import pandas as pd
import numpy as np

In [4]:
s1 = pd.Series([1,2,2,7,'Sachin',77.5])
print(s1.head())
print()
print(s1.head(3))

0         1
1         2
2         2
3         7
4    Sachin
dtype: object

0    1
1    2
2    2
dtype: object

In [5]:
df = pd.DataFrame({"A":[4, 5, 2, 6],
"B":[11, 2, 5, 8],
"C":[1, 8, 66, 4]})
df

   A   B   C
0  4  11   1
1  5   2   8
2  2   5  66
3  6   8   4

In [6]:
df.idxmax(axis = 0)

A    3
B    0
C    2
dtype: int64

In [19]:
name = pd.Series(['Sanjeev','Keshav','Rahul'])
age = pd.Series([37,42,38])
designation = pd.Series(['Manager','Clerk','Accountant'])
d1 = {'Name':name,'Age':age,'Designation':designation}
df = pd.DataFrame(d1)
print(df)
print()
df1 = df.sort_values(by='Age')
print(df1)

      Name  Age Designation
0  Sanjeev   37     Manager
1   Keshav   42       Clerk
2    Rahul   38  Accountant

      Name  Age Designation
0  Sanjeev   37     Manager
2    Rahul   38  Accountant
1   Keshav   42       Clerk

In [ ]:
df2 = df.sort_values(by='Name',ascending=0)
print(df2)

      Name  Age Designation
0  Sanjeev   37     Manager
2    Rahul   38  Accountant
1   Keshav   42       Clerk

In [21]:
df = pd.DataFrame(index=[0,1,2,3,4,5],columns=['one','two'])
print(df['one'].sum())

0

In [25]:
d = {'Player':['Hardik Pandya','K L Rahul','AndreRussel','Jasprit Bumrah','ViratKohli','Rohit Sharma'],
'Team':['Mumbai Indians','Kings Eleven','Kolkata Knight Riders','MumbaiIndians','RCB','Mumbai Indians'],
'Category':['Batsman','Batsman','Batsman','Bowler','Batsman','Batsman'] ,
'Bidprice':[13,12,7,10,17,15],
'Runs':[1000,2400,900,200,3600,3700]}
df = pd.DataFrame(d)
print(df)
print()
print(df.iloc[:2,:])
print()
print(df.iloc[-3:,:])

           Player                   Team Category  Bidprice  Runs
0   Hardik Pandya         Mumbai Indians  Batsman        13  1000
1       K L Rahul           Kings Eleven  Batsman        12  2400
2     AndreRussel  Kolkata Knight Riders  Batsman         7   900
3  Jasprit Bumrah          MumbaiIndians   Bowler        10   200
4      ViratKohli                    RCB  Batsman        17  3600
5    Rohit Sharma         Mumbai Indians  Batsman        15  3700

          Player            Team Category  Bidprice  Runs
0  Hardik Pandya  Mumbai Indians  Batsman        13  1000
1      K L Rahul    Kings Eleven  Batsman        12  2400

           Player            Team Category  Bidprice  Runs
3  Jasprit Bumrah   MumbaiIndians   Bowler        10   200
4      ViratKohli             RCB  Batsman        17  3600
5    Rohit Sharma  Mumbai Indians  Batsman        15  3700

In [27]:
print(df[df['Bidprice']==df['Bidprice'].max()])

       Player Team Category  Bidprice  Runs
4  ViratKohli  RCB  Batsman        17  3600

In [28]:
print(df.groupby('Team').Player.count())

Team
Kings Eleven             1
Kolkata Knight Riders    1
Mumbai Indians           2
MumbaiIndians            1
RCB                      1
Name: Player, dtype: int64

In [31]:
val = df.groupby('Team')
print(val[['Player','Bidprice']].max())

                               Player  Bidprice
Team
Kings Eleven                K L Rahul        12
Kolkata Knight Riders     AndreRussel         7
Mumbai Indians           Rohit Sharma        15
MumbaiIndians          Jasprit Bumrah        10
RCB                        ViratKohli        17

In [33]:
print(df.groupby(['Team']).Runs.mean())

Team
Kings Eleven             2400.0
Kolkata Knight Riders     900.0
Mumbai Indians           2350.0
MumbaiIndians             200.0
RCB                      3600.0
Name: Runs, dtype: float64

In [35]:
print(df.sort_values(by='Bidprice'))

           Player                   Team Category  Bidprice  Runs
2     AndreRussel  Kolkata Knight Riders  Batsman         7   900
3  Jasprit Bumrah          MumbaiIndians   Bowler        10   200
1       K L Rahul           Kings Eleven  Batsman        12  2400
0   Hardik Pandya         Mumbai Indians  Batsman        13  1000
5    Rohit Sharma         Mumbai Indians  Batsman        15  3700
4      ViratKohli                    RCB  Batsman        17  3600

In [37]:
df1.dropna(axis=1)

      Name  Age Designation
0  Sanjeev   37     Manager
2    Rahul   38  Accountant
1   Keshav   42       Clerk

In [38]:
df1.dropna(axis=0)

      Name  Age Designation
0  Sanjeev   37     Manager
2    Rahul   38  Accountant
1   Keshav   42       Clerk

In [41]:
df1 = pd.DataFrame({'key':['a','b','c','d'], 'value':[1,2,3,4]})
df2 = pd.DataFrame({'key':['a','b','e','b'], 'value':[5,6,7,8]})
df3 = df1.merge(df2, on = 'key', how = 'outer')
df3

  key  value_x  value_y
0   a      1.0      5.0
1   b      2.0      6.0
2   b      2.0      8.0
3   c      3.0      NaN
4   d      4.0      NaN
5   e      NaN      7.0

In [43]:
df3 = df1.merge(df2, on = 'key', how = 'inner')
df3

  key  value_x  value_y
0   a        1        5
1   b        2        6
2   b        2        8

In [44]:
df3 = df1.merge(df2, on = 'key', how = 'right')
df3

  key  value_x  value_y
0   a      1.0        5
1   b      2.0        6
2   e      NaN        7
3   b      2.0        8

In [45]:
df3 = df1.merge(df2, on = 'key', how = 'left')
df3

  key  value_x  value_y
0   a        1      5.0
1   b        2      6.0
2   b        2      8.0
3   c        3      NaN
4   d        4      NaN

In [46]:
d1 = { 'CS':[45,55,78,95,99,97], 'IP':[87,89,98,94,78,77] }
df = pd.DataFrame(d1)
print(df['CS'].sum())

469

In [48]:
l = [[10,20],[20,30],[30,40]]
df = pd.DataFrame(l,columns=['CS','IP'])
print(df)

   CS  IP
0  10  20
1  20  30
2  30  40

In [49]:
df.shape

(3, 2)

In [51]:
data = {
    'MaxTemp': [45, 34, 48, 32, 44, 39],
    'MinTemp': [30, 24, 34, 22, 29, 37],
    'City': ['Delhi', 'Guwahati', 'Chennai', 'Bangluru', 'Mumbai', 'Jaipur'],
    'RainFall': [25.6, 41.5, 36.8, 40.2, 38.5, 24.9]
}

df = pd.DataFrame(data)

In [52]:
print(df.sum(axis=0))

MaxTemp                                          242
MinTemp                                          176
City        DelhiGuwahatiChennaiBangluruMumbaiJaipur
RainFall                                       207.5
dtype: object

In [53]:
print(df['MaxTemp'].mean())

40.333333333333336

In [57]:
df[['MinTemp', 'RainFall']][:4].mean()

MinTemp     27.500
RainFall    36.025
dtype: float64

In [58]:
df = pd.DataFrame([45,50,41,56], index = [True, False, True, False])
print(df.iloc[True])

TypeError: Cannot index by location index with a non-integer key

In [59]:
xiia = {'sub':['eng','mat','ip','phy','che','bio'],'id':['302','041','065','042','043','044']}
xiic = {'sub':['eng','mat','ip','acc','bst','eco'],'id':['302','041','065','055','056','057']}
df1 = pd.DataFrame(xiia)
print(df1)
print()
df2 = pd.DataFrame(xiic)
print(df2)
print()
print(df1.merge(df2,on='id'))
print()
print(df1.merge(df2,on='id',how='outer'))

   sub   id
0  eng  302
1  mat  041
2   ip  065
3  phy  042
4  che  043
5  bio  044

   sub   id
0  eng  302
1  mat  041
2   ip  065
3  acc  055
4  bst  056
5  eco  057

  sub_x   id sub_y
0   eng  302   eng
1   mat  041   mat
2    ip  065    ip

  sub_x   id sub_y
0   mat  041   mat
1   phy  042   NaN
2   che  043   NaN
3   bio  044   NaN
4   NaN  055   acc
5   NaN  056   bst
6   NaN  057   eco
7    ip  065    ip
8   eng  302   eng

In [61]:
df.tail(4)

        0
True   45
False  50
True   41
False  56

In [63]:
K = pd.Series([2,4,6,8,10,12,14])
print(K.quantile([0.50,0.75]))

0.50     8.0
0.75    11.0
dtype: float64

In [64]:
df = df.drop(0)

In [65]:
L = [['S101','Amy',70], ['S102','Risha',69], ['S104','Susan',75], ['S105','George',82]]
df = pd.DataFrame(L,index=[1,2,3,4],columns=['ID','Name','Points'])
print(df)

     ID    Name  Points
1  S101     Amy      70
2  S102   Risha      69
3  S104   Susan      75
4  S105  George      82

In [67]:
df = pd.DataFrame({"Quarter1":[2000, 4000, 5000, 4400, 10000],
"Quarter2":[5800, 2500, 5400, 3000, 2900],
"Quarter3":[20000, 16000, 7000, 3600, 8200],
"Quarter4":[1400, 3700, 1700, 2000, 6000]})

print(df.mean(axis=0,skipna=True))
print()
print(df.mean(axis=1,skipna=True))

Quarter1     5080.0
Quarter2     3920.0
Quarter3    10960.0
Quarter4     2960.0
dtype: float64

0    7300.0
1    6550.0
2    4775.0
3    3250.0
4    6775.0
dtype: float64

In [68]:
print(df.sum(axis=0))

Quarter1    25400
Quarter2    19600
Quarter3    54800
Quarter4    14800
dtype: int64

In [69]:
print(df.median())

Quarter1    4400.0
Quarter2    3000.0
Quarter3    8200.0
Quarter4    2000.0
dtype: float64

In [71]:
x1 = [[10,150],[40,451],[15,302],[40,703]]
df1 = pd.DataFrame(x1,columns=['mark1','mark2'])
x2 = [[30,20],[20,25],[20,30],[5,30]]
df2 = pd.DataFrame(x2,columns=['mark1','mark2'])
print(df1)
print()
print(df2)

   mark1  mark2
0     10    150
1     40    451
2     15    302
3     40    703

   mark1  mark2
0     30     20
1     20     25
2     20     30
3      5     30

In [72]:
print(df1.add(df2))

   mark1  mark2
0     40    170
1     60    476
2     35    332
3     45    733

In [73]:
print(df1.sub(df2))

   mark1  mark2
0    -20    130
1     20    426
2     -5    272
3     35    673

In [75]:
df1 = df1.rename(index={0:'zero',1:'one'})
df1

      mark1  mark2
zero     10    150
one      40    451
2        15    302
3        40    703

In [76]:
d = {'Student':['Ali','Ali','Tom','Tom'],
'House':['Red','Red','Blue','Blue'],
'Points':[50,70,60,80]}
df = pd.DataFrame(d)
df1 = df.pivot_table(index='Student',columns='House',values='Points',aggfunc='sum')
print(df1)

House     Blue    Red
Student
Ali        NaN  120.0
Tom      140.0    NaN

In [77]:
d = {'Product':['Apple','Pear','Banana','Grapes'],'Quantity':[100,150,200,250],
'Cost':[1000,1500,1200,900]}
df = pd.DataFrame(d)
df1 = pd.DataFrame([df['Quantity'].max(),df['Cost'].mean()],index=['Quantity','Cost'])
df1

               0
Quantity   250.0
Cost      1150.0

In [83]:
df1 = pd.DataFrame({'Icecream':['Vanila','ButterScotch','Caramel'] ,
'Cookies':['Goodday','Britannia', 'Oreo']})
df2 = pd.DataFrame({'Chocolate':['DairyMilk','Kitkat'],'Icecream':['Vanila','ButterScotch'],'Cookies':['Hide and Seek','Britannia']})
df2.reindex_like(df1)
print(df2)

   Chocolate      Icecream        Cookies
0  DairyMilk        Vanila  Hide and Seek
1     Kitkat  ButterScotch      Britannia

In [84]:
df1 = df.drop(index=[2,3],axis=0)
df1

  Product  Quantity  Cost
0   Apple       100  1000
1    Pear       150  1500

In [89]:
df1 = pd.DataFrame({
    'First': [10, 20, 30, 40],
    'Second': [4, 5, 7, 9],
    'Third': [30, 40, 50, 70]
})

df2 = pd.DataFrame({
    'First': [17, 18, 19, 20],
    'Second': [14, 15, 17, 19],
    'Third': [13, 14, 15, 17]
})

In [90]:
print(df1.add(df2))

   First  Second  Third
0     27      18     43
1     38      20     54
2     49      24     65
3     60      28     87

In [91]:
df1 = df1.sort_values(by='Second',ascending=False)
df1

   First  Second  Third
3     40       9     70
2     30       7     50
1     20       5     40
0     10       4     30

In [92]:
df2 = df2.rename(index={0:'a',1:'b',2:'c',3:'d'})
df2

   First  Second  Third
a     17      14     13
b     18      15     14
c     19      17     15
d     20      19     17

In [93]:
print(df1[df1['Third']>45])

   First  Second  Third
3     40       9     70
2     30       7     50

In [95]:
student_df = pd.DataFrame({'Name':['Ananmay','Aditi','Mehak','Kriti'],'Class':['XI','XI','XI','XI'],'Marks':[95,82,65,45]},index=[1,2,3,4])
data = {'Name':'Sohail','Class':'XII','Marks':77}
newstd = pd.DataFrame(data, index=[5])
student_df = pd.concat([student_df, newstd])
student_df

      Name Class  Marks
1  Ananmay    XI     95
2    Aditi    XI     82
3    Mehak    XI     65
4    Kriti    XI     45
5   Sohail   XII     77

In [97]:
car = {'Name':['Innova','Tavera','Royal','Scorpio'],'Price':[300000,800000,250000,650000]}
df = pd.DataFrame(car,index=[1,2,3,4])
print(df[df.Price==df.Price.max()])

     Name   Price
2  Tavera  800000

In [98]:
print(df1.count())

First     4
Second    4
Third     4
dtype: int64

In [100]:
df=pd.DataFrame({"a":[13, 24, 43, 4],"b":[51, 26, 37, 48]})
print(df)
print()
df.sort_values('a', inplace = True)
print(df)

    a   b
0  13  51
1  24  26
2  43  37
3   4  48

    a   b
3   4  48
0  13  51
1  24  26
2  43  37

In [108]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily','Michael','Matthew', 'Lara', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.NaN, 9, 20,14.5, np.NaN, 8, 19],
'attempts' : [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes','no','yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

df = pd.DataFrame(exam_data)

In [109]:
df = df.dropna()
df

        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

In [110]:
print(df.pivot_table(columns=['qualify'],values=['score','attempts'],aggfunc='sum'))

qualify     no   yes
attempts   7.0   8.0
score     26.0  82.5

In [111]:
print(df[df['qualify']=='yes'].name)

0    Anastasia
2    Katherine
5      Michael
6      Matthew
9        Jonas
Name: name, dtype: object

In [112]:
data = {
    'A': [12, 4, 5, 44, 1],
    'B': [5, 2, 54, 3, 2],
    'C': [20, 16, 7, 3, 8],
    'D': [14, 3, 17, 2, 6]
}

df = pd.DataFrame(data)

In [114]:
df = df.rename(index={0:'Zero',1:'One',2:'Two',3:'Three'})
df

        A   B   C   D
Zero   12   5  20  14
One     4   2  16   3
Two     5  54   7  17
Three  44   3   3   2
4       1   2   8   6

In [115]:
print(df.mean(axis=0))

A    13.2
B    13.2
C    10.8
D     8.4
dtype: float64

In [117]:
df2 = {'col1': 5, 'col2': 12, 'col3': 33, 'col4':3}

new_row = pd.DataFrame([df2])
df = pd.concat([df, new_row], ignore_index=True)
df

      A     B     C     D  col1  col2  col3  col4
0  12.0   5.0  20.0  14.0   NaN   NaN   NaN   NaN
1   4.0   2.0  16.0   3.0   NaN   NaN   NaN   NaN
2   5.0  54.0   7.0  17.0   NaN   NaN   NaN   NaN
3  44.0   3.0   3.0   2.0   NaN   NaN   NaN   NaN
4   1.0   2.0   8.0   6.0   NaN   NaN   NaN   NaN
5   NaN   NaN   NaN   NaN   5.0  12.0  33.0   3.0

In [130]:
df = pd.DataFrame({
    'Emp_ID': [100, 110, 120, 130, 140],
    'Name': ['Kabir', 'Rishav', 'Seema', 'David', 'Ruchi'],
    'Dept': ['IT', 'Finance', 'IT', 'IT', 'HRD'],
    'Salary': [34000, 28500, 13500, 41000, 17000],
    'Status': ['Regular', 'Regular', 'Contract', 'Regular', 'Contract']
})

df

   Emp_ID    Name     Dept  Salary    Status
0     100   Kabir       IT   34000   Regular
1     110  Rishav  Finance   28500   Regular
2     120   Seema       IT   13500  Contract
3     130   David       IT   41000   Regular
4     140   Ruchi      HRD   17000  Contract

In [131]:
print(df.groupby('Status')['Salary'].mean())

Status
Contract    15250.0
Regular     34500.0
Name: Salary, dtype: float64

In [132]:
df = df.sort_values(by='Salary',ascending=False)
df

   Emp_ID    Name     Dept  Salary    Status
3     130   David       IT   41000   Regular
0     100   Kabir       IT   34000   Regular
1     110  Rishav  Finance   28500   Regular
4     140   Ruchi      HRD   17000  Contract
2     120   Seema       IT   13500  Contract

In [133]:
df.Salary[df.Status=='Contract']=19000
df

/tmp/ipykernel_149959/1794336279.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.Salary[df.Status=='Contract']=19000
/tmp/ipykernel_149959/1794336279.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Salary[df.Status=='Contract']=19000

   Emp_ID    Name     Dept  Salary    Status
3     130   David       IT   41000   Regular
0     100   Kabir       IT   34000   Regular
1     110  Rishav  Finance   28500   Regular
4     140   Ruchi      HRD   19000  Contract
2     120   Seema       IT   19000  Contract

In [134]:
print(df.groupby('Dept').count().Name)

Dept
Finance    1
HRD        1
IT         3
Name: Name, dtype: int64

In [135]:
print(df[df['Status']=='Contract'].max().Salary)

19000

In [136]:
print(df.iloc[3:4,:])

   Emp_ID   Name Dept  Salary    Status
4     140  Ruchi  HRD   19000  Contract

In [137]:
del df['Status']

In [138]:
print(df[df.Dept=='IT'].max().Salary)

41000

In [139]:
df = df.drop([0,4])
df

   Emp_ID    Name     Dept  Salary
3     130   David       IT   41000
1     110  Rishav  Finance   28500
2     120   Seema       IT   19000

In [140]:
df = pd.DataFrame({
    'A': [56, -29, 83],
    'B': [71, -63, -60],
    'C': [-13, 34, 71]
}, index=[1, 2, 3])

df

    A   B   C
1  56  71 -13
2 -29 -63  34
3  83 -60  71

In [141]:
df[df<0]=0
df

    A   B   C
1  56  71   0
2   0   0  34
3  83   0  71

In [142]:
print(df[df>50].count().sum())

4

In [143]:
print('No of Even Numbers:',df[df%2==0].count().sum())
print('No of Odd Numbers:',df[df%2==1].count().sum())

No of Even Numbers: 6
No of Odd Numbers: 3

In [144]:
data = {
    'employee': ['Sahay', 'George', 'Priya', 'Manila', 'Raina', 'Manila', 'Priya'],
    'sales': [125600, 235600, 213400, 189000, 456000, 172000, 201400],
    'Quarter': [1, 1, 1, 1, 1, 2, 2],
    'State': ['Delhi', 'Tamil Nadu', 'Kerala', 'Haryana', 'West Bengal', 'Haryana', 'Kerala']
}

df = pd.DataFrame(data)
df

  employee   sales  Quarter        State
0    Sahay  125600        1        Delhi
1   George  235600        1   Tamil Nadu
2    Priya  213400        1       Kerala
3   Manila  189000        1      Haryana
4    Raina  456000        1  West Bengal
5   Manila  172000        2      Haryana
6    Priya  201400        2       Kerala

In [146]:
print(df.groupby('State').sum().sales)

State
Delhi          125600
Haryana        361000
Kerala         414800
Tamil Nadu     235600
West Bengal    456000
Name: sales, dtype: int64

In [147]:
print(df.groupby('employee').sum().sales)

employee
George    235600
Manila    361000
Priya     414800
Raina     456000
Sahay     125600
Name: sales, dtype: int64

In [148]:
print(df.groupby(['employee','State']).sum().sales)

employee  State
George    Tamil Nadu     235600
Manila    Haryana        361000
Priya     Kerala         414800
Raina     West Bengal    456000
Sahay     Delhi          125600
Name: sales, dtype: int64

In [153]:
print(df.groupby('State')['sales'].mean())
print()
print(df.groupby('State')['sales'].median())
print()
print(df.groupby('State')['sales'].min())

State
Delhi          125600.0
Haryana        180500.0
Kerala         207400.0
Tamil Nadu     235600.0
West Bengal    456000.0
Name: sales, dtype: float64

State
Delhi          125600.0
Haryana        180500.0
Kerala         207400.0
Tamil Nadu     235600.0
West Bengal    456000.0
Name: sales, dtype: float64

State
Delhi          125600
Haryana        172000
Kerala         201400
Tamil Nadu     235600
West Bengal    456000
Name: sales, dtype: int64

In [150]:
print(df.groupby('Quarter').max().sales)

Quarter
1    456000
2    201400
Name: sales, dtype: int64

In [151]:
print(df.pivot_table(index='State',values='sales',aggfunc='max'))

              sales
State
Delhi        125600
Haryana      189000
Kerala       213400
Tamil Nadu   235600
West Bengal  456000