In [ ]:
import numpy as np
import pandas as pd 
from khayyam import JalaliDatetime
from datetime import timedelta
import holidays

In [ ]:
df = pd.read_csv('data/traffic.csv', parse_dates=['DateTime'])
df.head()

In [7]:
from datetime import datetime as dt
miladi_date = dt(1998,10,29)
print(f'Miladi date = {miladi_date}')

from khayyam import JalaliDatetime
shamsi_date = JalaliDatetime(miladi_date)
print('Sahmsi date = ', shamsi_date)

Miladi date = 1998-10-29 00:00:00
Sahmsi date =  1377-08-07 00:00:00.000000

In [ ]:
df['JalaliDateTime'] = df["DateTime"].apply(JalaliDatetime)
df

                 DateTime  Junction  Car              JalaliDateTime
0     2020-05-02 00:00:00         1   25  1399-02-13 00:00:00.000000
1     2020-05-02 01:00:00         1   23  1399-02-13 01:00:00.000000
2     2020-05-02 02:00:00         1   20  1399-02-13 02:00:00.000000
3     2020-05-02 03:00:00         1   12  1399-02-13 03:00:00.000000
4     2020-05-02 04:00:00         1   19  1399-02-13 04:00:00.000000
...                   ...       ...  ...                         ...
48115 2021-12-30 19:00:00         4   26  1400-10-09 19:00:00.000000
48116 2021-12-30 20:00:00         4   55  1400-10-09 20:00:00.000000
48117 2021-12-30 21:00:00         4   31  1400-10-09 21:00:00.000000
48118 2021-12-30 22:00:00         4   37  1400-10-09 22:00:00.000000
48119 2021-12-30 23:00:00         4   27  1400-10-09 23:00:00.000000

[48120 rows x 4 columns]

In [ ]:
def cal_hour(hour):
    time = hour.strftime('%H:%M:%S')
    if '00:00:00' <= time <= '05:59:59':
        return 0

    elif '06:00:00' <= time <= '11:59:59':
        return 1
    
    elif '12:00:00' <= time <= '14:59:59':
        return 2
    elif '15:00:00' <= time <= '17:59:59':
        return 3
    elif '18:00:00' <= time <= '21:59:59':
        return 4
    elif '22:00:00' <= time <= '23:59:59':
        return 5


df['hour'] = df["JalaliDateTime"].apply(cal_hour)
df.head()

                 DateTime  Junction  Car              JalaliDateTime  hour
0     2020-05-02 00:00:00         1   25  1399-02-13 00:00:00.000000     0
1     2020-05-02 01:00:00         1   23  1399-02-13 01:00:00.000000     0
2     2020-05-02 02:00:00         1   20  1399-02-13 02:00:00.000000     0
3     2020-05-02 03:00:00         1   12  1399-02-13 03:00:00.000000     0
4     2020-05-02 04:00:00         1   19  1399-02-13 04:00:00.000000     0
...                   ...       ...  ...                         ...   ...
48115 2021-12-30 19:00:00         4   26  1400-10-09 19:00:00.000000     4
48116 2021-12-30 20:00:00         4   55  1400-10-09 20:00:00.000000     4
48117 2021-12-30 21:00:00         4   31  1400-10-09 21:00:00.000000     4
48118 2021-12-30 22:00:00         4   37  1400-10-09 22:00:00.000000     5
48119 2021-12-30 23:00:00         4   27  1400-10-09 23:00:00.000000     5

[48120 rows x 5 columns]

In [ ]:
iran_holidays = holidays.IR()
df['IsHoliday'] = df['JalaliDateTime'].apply(lambda d: 1 if d in iran_holidays else 0)
df.head()

,DateTime,Junction,Car,JalaliDateTime,hour,IsHoliday,IsCold
0,2020-05-02 00:00:00,1,25,1399-02-13 00:00:00.000000,0,0,0
1,2020-05-02 01:00:00,1,23,1399-02-13 01:00:00.000000,0,0,0
2,2020-05-02 02:00:00,1,20,1399-02-13 02:00:00.000000,0,0,0
3,2020-05-02 03:00:00,1,12,1399-02-13 03:00:00.000000,0,0,0
4,2020-05-02 04:00:00,1,19,1399-02-13 04:00:00.000000,0,0,0
...,...,...,...,...,...,...,...
48115,2021-12-30 19:00:00,4,26,1400-10-09 19:00:00.000000,4,0,1
48116,2021-12-30 20:00:00,4,55,1400-10-09 20:00:00.000000,4,0,1
48117,2021-12-30 21:00:00,4,31,1400-10-09 21:00:00.000000,4,0,1
48118,2021-12-30 22:00:00,4,37,1400-10-09 22:00:00.000000,5,0,1
48119,2021-12-30 23:00:00,4,27,1400-10-09 23:00:00.000000,5,0,1

In [ ]:
df['IsCold'] = df['JalaliDateTime'].apply(lambda d: 1 if d.month >= 7 else 0)
df.head()

,DateTime,Junction,Car,JalaliDateTime,hour,IsHoliday,IsCold
0,2020-05-02 00:00:00,1,25,1399-02-13 00:00:00.000000,0,False,0
1,2020-05-02 01:00:00,1,23,1399-02-13 01:00:00.000000,0,False,0
2,2020-05-02 02:00:00,1,20,1399-02-13 02:00:00.000000,0,False,0
3,2020-05-02 03:00:00,1,12,1399-02-13 03:00:00.000000,0,False,0
4,2020-05-02 04:00:00,1,19,1399-02-13 04:00:00.000000,0,False,0
...,...,...,...,...,...,...,...
48115,2021-12-30 19:00:00,4,26,1400-10-09 19:00:00.000000,4,False,1
48116,2021-12-30 20:00:00,4,55,1400-10-09 20:00:00.000000,4,False,1
48117,2021-12-30 21:00:00,4,31,1400-10-09 21:00:00.000000,4,False,1
48118,2021-12-30 22:00:00,4,37,1400-10-09 22:00:00.000000,5,False,1
48119,2021-12-30 23:00:00,4,27,1400-10-09 23:00:00.000000,5,False,1

In [ ]:
df = pd.concat([df, pd.get_dummies(df['Junction'], prefix='Junc')],axis=1)
df.head()