In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("data/students_performance.csv")
df.head()

  student name  reading score  math score  writing score
0      Melanie             58          49             25
1    Gabriella             45          72             88
2       Ashley             46          27             22
3        James             84           2             77
4      William             69          35             26

In [3]:
subjects = ["math score", "reading score", "writing score"]

mean_val = {}
median_val = {} 
mode_val = {}

for subject in subjects:

    mean_val[subject] = round(df[subject].mean(), 2)
    
    median_val[subject] = round(df[subject].median(), 2)
    
    mode_result = df[subject].mode()
    if len(mode_result) > 0:
        mode_val[subject] = round(float(mode_result.iloc[0]), 2)
    else:
        mode_val[subject] = float('nan')

In [4]:
variance_val = {}
std_val = {}
range_val = {}

for subject in subjects:

    variance_val[subject] = round(df[subject].var(ddof=0), 2)
    
    std_val[subject] = round(df[subject].std(ddof=0), 2)
    
    range_val[subject] = round(df[subject].max() - df[subject].min(), 2)

In [5]:
df["total score"] = df[['math score', 'reading score', 'writing score']].mean(axis=1)
df.head()

  student name  reading score  math score  writing score  total score
0      Melanie             58          49             25    44.000000
1    Gabriella             45          72             88    68.333333
2       Ashley             46          27             22    31.666667
3        James             84           2             77    54.333333
4      William             69          35             26    43.333333

In [6]:
Q1 = df['total score'].quantile(0.25)
Q3 = df['total score'].quantile(0.75)
IQR = Q3 - Q1

In [7]:
less_than_Q1 = round(len(df[df['total score'] < Q1]) / len(df) * 100 , 2)
between_Q1_Q3 = round(len(df[(df['total score'] >= Q1) & (df['total score'] <= Q3)]) / len(df) * 100 , 2)
more_than_Q3 = round(len(df[df['total score'] > Q3]) / len(df) * 100 , 2)