In [ ]:
import pandas as pd

df = pd.read_csv('data/data.csv')
df.head()

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,GRADE,COMPRATE,HIREDATE_STRING,GVT_TYPE_OF_APPT,OBJECTID
0,Scott,Pitzer,Facilities Systems Specialist,DBH,12,90805.0,1987/10/01,CS - Reg,1
1,Pauline,Oboite,NURSE,DBH,05,76510.0,2000/02/14,CS - Reg,2
2,Dawn,Fong,Special Projects Coordinator,DCG,12,90805.0,2020/03/16,CS - Term,3
3,Sonya,Kingsland,Behavioral Health Technician,DBH,08,70600.0,1988/06/07,CS - Reg,4
4,Octavia,Fletcher,Behavioral Health Technician,DBH,08,70600.0,1995/09/18,CS - Reg,5

In [2]:
df['avg_sal'] = df.groupby('DESCRSHORT')['COMPRATE'].transform('mean')
df.head(3)

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,GRADE,COMPRATE,HIREDATE_STRING,GVT_TYPE_OF_APPT,OBJECTID,avg_sal
0,Scott,Pitzer,Facilities Systems Specialist,DBH,12,90805.0,1987/10/01,CS - Reg,1,92360.327989
1,Pauline,Oboite,NURSE,DBH,05,76510.0,2000/02/14,CS - Reg,2,92360.327989
2,Dawn,Fong,Special Projects Coordinator,DCG,12,90805.0,2020/03/16,CS - Term,3,99073.815072

In [3]:
above_avg = df[df['COMPRATE'] > df['avg_sal']]
above_avg.head(3)

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,GRADE,COMPRATE,HIREDATE_STRING,GVT_TYPE_OF_APPT,OBJECTID,avg_sal
5,Emily,Simmons,Attorney Advisor,DCHR,14,145969.0,2018/04/17,LS - Reg,6,85956.275508
9,Shaun,Parker,VIDEOGRAPHER,DCG,13,133558.0,2006/03/06,CS - Reg,10,99073.815072
12,Danielle,Lee,HR Spec (Recruit & Placement),DCHR,12,90805.0,2019/01/22,CS - Reg,13,85956.275508

In [4]:
above_average_employees_df = above_avg[
    ['OBJECTID', 'DESCRSHORT', 'COMPRATE']
]
above_average_employees_df.head(3)

    OBJECTID DESCRSHORT  COMPRATE
5          6       DCHR  145969.0
9         10        DCG  133558.0
12        13       DCHR   90805.0

In [5]:
above_average_employees_df = above_average_employees_df.sort_values('OBJECTID')
above_average_employees_df.head(3)

    OBJECTID DESCRSHORT  COMPRATE
5          6       DCHR  145969.0
9         10        DCG  133558.0
12        13       DCHR   90805.0

In [6]:
df['HIREDATE'] = pd.to_datetime(df['HIREDATE_STRING'])
df.head(3)

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,GRADE,COMPRATE,HIREDATE_STRING,GVT_TYPE_OF_APPT,OBJECTID,avg_sal,HIREDATE
0,Scott,Pitzer,Facilities Systems Specialist,DBH,12,90805.0,1987/10/01,CS - Reg,1,92360.327989,1987-10-01
1,Pauline,Oboite,NURSE,DBH,05,76510.0,2000/02/14,CS - Reg,2,92360.327989,2000-02-14
2,Dawn,Fong,Special Projects Coordinator,DCG,12,90805.0,2020/03/16,CS - Term,3,99073.815072,2020-03-16

In [7]:
df['is_loyal'] = df['HIREDATE'].dt.year < 2000
df.head(3)

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,GRADE,COMPRATE,HIREDATE_STRING,GVT_TYPE_OF_APPT,OBJECTID,avg_sal,HIREDATE,is_loyal
0,Scott,Pitzer,Facilities Systems Specialist,DBH,12,90805.0,1987/10/01,CS - Reg,1,92360.327989,1987-10-01,True
1,Pauline,Oboite,NURSE,DBH,05,76510.0,2000/02/14,CS - Reg,2,92360.327989,2000-02-14,False
2,Dawn,Fong,Special Projects Coordinator,DCG,12,90805.0,2020/03/16,CS - Term,3,99073.815072,2020-03-16,False

In [8]:
dept_stats = df.groupby('DESCRSHORT').agg(
    total_employees=('OBJECTID', 'count'),
    loyal_employees=('is_loyal', 'sum')
).reset_index()
dept_stats.head(3)

  DESCRSHORT  total_employees  loyal_employees
0       ABCA               62                4
1       ABRA              112                8
2        ANC               12                4

In [9]:
dept_stats = dept_stats[dept_stats['total_employees'] >= 10]
dept_stats.head(3)

  DESCRSHORT  total_employees  loyal_employees
0       ABCA               62                4
1       ABRA              112                8
2        ANC               12                4

In [10]:
dept_stats['Loyal_Employee_Percentage'] = (
    dept_stats['loyal_employees'] / dept_stats['total_employees'] * 100
).round(2)
dept_stats.head(3)

  DESCRSHORT  total_employees  loyal_employees  Loyal_Employee_Percentage
0       ABCA               62                4                       6.45
1       ABRA              112                8                       7.14
2        ANC               12                4                      33.33

In [11]:
dept_stats = dept_stats[dept_stats['loyal_employees'] > 0]
dept_stats.head(3)

  DESCRSHORT  total_employees  loyal_employees  Loyal_Employee_Percentage
0       ABCA               62                4                       6.45
1       ABRA              112                8                       7.14
2        ANC               12                4                      33.33

In [12]:
loyal_percentage_df = dept_stats[
    ['DESCRSHORT', 'Loyal_Employee_Percentage']
].sort_values(by='Loyal_Employee_Percentage', ascending=False)

loyal_percentage_df.head(3)

   DESCRSHORT  Loyal_Employee_Percentage
2         ANC                      33.33
69        OEA                      33.33
93      RPTAC                      27.78

In [13]:
df['HIREDATE_STRING'] = pd.to_datetime(df['HIREDATE_STRING'], errors='coerce')
df['year'] = df['HIREDATE_STRING'].dt.year
df.head(3)

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,GRADE,COMPRATE,HIREDATE_STRING,GVT_TYPE_OF_APPT,OBJECTID,avg_sal,HIREDATE,is_loyal,year
0,Scott,Pitzer,Facilities Systems Specialist,DBH,12,90805.0,1987-10-01,CS - Reg,1,92360.327989,1987-10-01,True,1987
1,Pauline,Oboite,NURSE,DBH,05,76510.0,2000-02-14,CS - Reg,2,92360.327989,2000-02-14,False,2000
2,Dawn,Fong,Special Projects Coordinator,DCG,12,90805.0,2020-03-16,CS - Term,3,99073.815072,2020-03-16,False,2020

In [14]:
df['quintile'] = pd.qcut(df['year'], q=5, labels=[5, 4, 3, 2, 1])
df.head(3)

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,GRADE,COMPRATE,HIREDATE_STRING,GVT_TYPE_OF_APPT,OBJECTID,avg_sal,HIREDATE,is_loyal,year,quintile
0,Scott,Pitzer,Facilities Systems Specialist,DBH,12,90805.0,1987-10-01,CS - Reg,1,92360.327989,1987-10-01,True,1987,5
1,Pauline,Oboite,NURSE,DBH,05,76510.0,2000-02-14,CS - Reg,2,92360.327989,2000-02-14,False,2000,5
2,Dawn,Fong,Special Projects Coordinator,DCG,12,90805.0,2020-03-16,CS - Term,3,99073.815072,2020-03-16,False,2020,2

In [15]:
avg_salary = df.groupby('quintile')['COMPRATE'].mean().round(2)
avg_salary

/tmp/ipykernel_2173075/2517972171.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_salary = df.groupby('quintile')['COMPRATE'].mean().round(2)

quintile
5    91370.20
4    95478.40
3    87175.93
2    73096.33
1    54346.88
Name: COMPRATE, dtype: float64

In [16]:
average_salary_by_quintile_df = avg_salary.reset_index(
    name='Average_Salary'
)
average_salary_by_quintile_df

  quintile  Average_Salary
0        5        91370.20
1        4        95478.40
2        3        87175.93
3        2        73096.33
4        1        54346.88

In [17]:
average_salary_by_quintile_df['quintile'] = average_salary_by_quintile_df['quintile'].astype(int)
average_salary_by_quintile_df

   quintile  Average_Salary
0         5        91370.20
1         4        95478.40
2         3        87175.93
3         2        73096.33
4         1        54346.88

In [18]:
average_salary_by_quintile_df = average_salary_by_quintile_df.rename(
    columns={'quintile': 'Tenure_Quintile'}
)
average_salary_by_quintile_df

   Tenure_Quintile  Average_Salary
0                5        91370.20
1                4        95478.40
2                3        87175.93
3                2        73096.33
4                1        54346.88

In [19]:
average_salary_by_quintile_df = average_salary_by_quintile_df.sort_values(
    'Tenure_Quintile',
    ascending=False
)

# Final result
average_salary_by_quintile_df

   Tenure_Quintile  Average_Salary
0                5        91370.20
1                4        95478.40
2                3        87175.93
3                2        73096.33
4                1        54346.88