<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آشنایی با کتابخانه پانداز (۲)  
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc"> بررسی دیتافریم
    </font>
</h2>

In [41]:
import pandas as pd
import numpy as np

df = pd.DataFrame([['Peykan', 'Red', 48, 990, 33],
       ['BMW X6', 'White', 335, 2320, 2400],
       ['Peugeot 206', 'Black', 105, 1025, 105],
       ['Tiba', 'White', 87, 1027, 120],
       ['Nissan Junior', 'Blue', 93, 1540, 230],
       ['Nissan Junior', 'Red', 93, 1540, 186],
       ['renault 5', 'Silver', 48, 850, 38]],
       index = ['a','b','c','d','e','f','g'],
       columns= ['model' , 'Color' , 'HP', 'Weight (KG)', 'price'])
df

           model   Color   HP  Weight (KG)  price
a         Peykan     Red   48          990     33
b         BMW X6   White  335         2320   2400
c    Peugeot 206   Black  105         1025    105
d           Tiba   White   87         1027    120
e  Nissan Junior    Blue   93         1540    230
f  Nissan Junior     Red   93         1540    186
g      renault 5  Silver   48          850     38

In [42]:
df.head()

           model  Color   HP  Weight (KG)  price
a         Peykan    Red   48          990     33
b         BMW X6  White  335         2320   2400
c    Peugeot 206  Black  105         1025    105
d           Tiba  White   87         1027    120
e  Nissan Junior   Blue   93         1540    230

In [43]:
df.tail()

           model   Color   HP  Weight (KG)  price
c    Peugeot 206   Black  105         1025    105
d           Tiba   White   87         1027    120
e  Nissan Junior    Blue   93         1540    230
f  Nissan Junior     Red   93         1540    186
g      renault 5  Silver   48          850     38

In [44]:
df.head(6)

           model  Color   HP  Weight (KG)  price
a         Peykan    Red   48          990     33
b         BMW X6  White  335         2320   2400
c    Peugeot 206  Black  105         1025    105
d           Tiba  White   87         1027    120
e  Nissan Junior   Blue   93         1540    230
f  Nissan Junior    Red   93         1540    186

In [45]:
df.sample(4 , random_state = 42)

           model  Color   HP  Weight (KG)  price
a         Peykan    Red   48          990     33
b         BMW X6  White  335         2320   2400
f  Nissan Junior    Red   93         1540    186
c    Peugeot 206  Black  105         1025    105

In [46]:
df.sample(frac=0.4 , random_state = 42)

           model  Color   HP  Weight (KG)  price
a         Peykan    Red   48          990     33
b         BMW X6  White  335         2320   2400
f  Nissan Junior    Red   93         1540    186

In [47]:
df.sample(frac=0.4, ignore_index=True , random_state = 42)

           model  Color   HP  Weight (KG)  price
0         Peykan    Red   48          990     33
1         BMW X6  White  335         2320   2400
2  Nissan Junior    Red   93         1540    186

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, a to g
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   model        7 non-null      object
 1   Color        7 non-null      object
 2   HP           7 non-null      int64
 3   Weight (KG)  7 non-null      int64
 4   price        7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 336.0+ bytes

In [49]:
df.describe()

               HP  Weight (KG)        price
count    7.000000     7.000000     7.000000
mean   115.571429  1327.428571   444.571429
std     99.354344   516.250539   865.250225
min     48.000000   850.000000    33.000000
25%     67.500000  1007.500000    71.500000
50%     93.000000  1027.000000   120.000000
75%     99.000000  1540.000000   208.000000
max    335.000000  2320.000000  2400.000000

In [50]:
df['Color'].value_counts()

Color
Red       2
White     2
Black     1
Blue      1
Silver    1
Name: count, dtype: int64

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc"> کار با دیتافریم
    </font>
</h2>

In [51]:
cars_dictionary = {
    "Color" :["Red", "White", "Black", "White", "Blue", "Red", "Silver"],
    "HP" :[48, 335, 105, 87, 93, 80, 48],
    "Weight (KG)": [990, 2320, 1025, 1027, 1540, 960, 850],
    "price" :[33, 2400, 105, 120, 230, 68, 38]
}

df = pd.DataFrame(cars_dictionary , index = [ "Peykan", "BMW X6", "Peugeot 206", "Tiba", "Nissan Junior", "Peykan Vanet", "renault 5"])

df

                Color   HP  Weight (KG)  price
Peykan            Red   48          990     33
BMW X6          White  335         2320   2400
Peugeot 206     Black  105         1025    105
Tiba            White   87         1027    120
Nissan Junior    Blue   93         1540    230
Peykan Vanet      Red   80          960     68
renault 5      Silver   48          850     38

In [52]:
df["Color"]

Peykan              Red
BMW X6            White
Peugeot 206       Black
Tiba              White
Nissan Junior      Blue
Peykan Vanet        Red
renault 5        Silver
Name: Color, dtype: object

In [53]:
df.Color

Peykan              Red
BMW X6            White
Peugeot 206       Black
Tiba              White
Nissan Junior      Blue
Peykan Vanet        Red
renault 5        Silver
Name: Color, dtype: object

In [54]:
for c in df.columns:
    print(c)
    print(df[c].count())

Color
7
HP
7
Weight (KG)
7
price
7

In [55]:
df[["Color" , "price"]]

                Color  price
Peykan            Red     33
BMW X6          White   2400
Peugeot 206     Black    105
Tiba            White    120
Nissan Junior    Blue    230
Peykan Vanet      Red     68
renault 5      Silver     38

In [56]:
df.iloc[2]

Color          Black
HP               105
Weight (KG)     1025
price            105
Name: Peugeot 206, dtype: object

In [59]:
df.loc["Tiba"]

Color          White
HP                87
Weight (KG)     1027
price            120
Name: Tiba, dtype: object

In [57]:
cars_dictionary = {
    "Color" :["Red", "White", "Black", "White", "Blue", "Red", "Silver"],
    "HP" :[48, 335, 105, 87, 93, 80, 48],
    "Weight (KG)": [990, 2320, 1025, 1027, 1540, 960, 850],
    "price" :[33, 2400, 105, 120, 230, 68, 38]
}

df2 = pd.DataFrame(cars_dictionary )

df2

    Color   HP  Weight (KG)  price
0     Red   48          990     33
1   White  335         2320   2400
2   Black  105         1025    105
3   White   87         1027    120
4    Blue   93         1540    230
5     Red   80          960     68
6  Silver   48          850     38

In [58]:
df2.loc[3]

Color          White
HP                87
Weight (KG)     1027
price            120
Name: 3, dtype: object