In [1]:
import pandas as pd 
import numpy as np

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    <code>apply</code> پارامترهای مهم تابع 
    </font>
</h2>

```python
DataFrame.apply(func, axis=0, raw=False, result_type=None, args=(), **kwargs)
```

<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=3>

| پارامتر     | توضیح |
| ----------- | ----------- |
| func        | تابعی که قصد داری روی دیتافریم اعمال کنیم.                                                                                                                                                                                                                                       |
| axis        | - اگر 0 باشد تابع روی هر ستون اعمال می‌شود. پیش‌فرض 0 است.<br>- اگر 1 باشد تابع روی هر سطر اعمال می‌شود.                                                                                                                                                                         |
| raw         | - اگر False باشد جنس سطر یا ستون ورودی func، دیتاسری خواهد بود. مقدار پیش‌فرض این پارامتر False است.<br>- اگر True باشد جنس سطر یا ستون ورودی func، آرایه نامپای خواهد بود. اگر func یکی از توابع نامپای باشد به دلیل بهبود عملکرد (performance) بهتر است raw را True قرار دهیم. |
| args        | پارامتر‌های موقعیتی (positional arguments) که تابع func می‌پذیرد.                                                                                                                                                                                                                |
| kwargs      | پارامتر‌های کلیدواژه‌ای (keyword arguments) که تابع func می‌پذیرد.                                                                                                                                                                                                               |
| result_type | جنس خروجی را مشخص می‌کند و فقط در صورتی مورد توجه قرار می‌گیرد که `axis=0‍` باشد. می‌تواند سه مقدار expand، reduce و broadcast را داشته باشد.                                                                                                                                    |

</font>
</div>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مثال اول
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    دیتافریمی به اسم <code>df</code> تعریف می‌کنیم و به دو روش جمع المان‌های هر سطر را محاسبه می‌کنیم.
</font>
</p>

In [2]:
df = pd.DataFrame()
df['col_1'] = [1,4,9,16]
df['col_2'] = [25,36,49,64]
df

   col_1  col_2
0      1     25
1      4     36
2      9     49
3     16     64

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
روش اول
</font>
</h3>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    تابعی به اسم <code>sum_row</code> می‌نویسیم و با استفاده از تابع <code>apply</code> آن را روی هر سطر از دیتافریم اعمال می‌کنیم.
</font>
</p>

In [3]:
def sum_row (row) :
    return row['col_2'] + row['col_1']

df['sum'] = df.apply(sum_row, axis=1)
df

   col_1  col_2  sum
0      1     25   26
1      4     36   40
2      9     49   58
3     16     64   80

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
روش دوم
</font>
</h3>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
   در روش دوم به جای تعریف و استفاده از توابع اضافه، می‌خواهیم فقط با استفاده از عبارت‌های لامدا جمع المان‌های هر سطر را به‌دست بیاوریم.
    <br>
    ابتدا لازم است ستون <code>sum</code> که از روش اول اضافه شده بود را حذف کنیم.
</font>
</p>

In [4]:
df.drop(['sum'], axis=1, inplace=True)
df['sum'] = df.apply(lambda row : row['col_1'] + row['col_2'], axis=1)
df

   col_1  col_2  sum
0      1     25   26
1      4     36   40
2      9     49   58
3     16     64   80

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مثال دوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در مثال دوم قصد داریم جمع المان‌های هر ستون  <code>df</code> که در مثال قبلی معرفی شد را حساب کنیم.
    
<br>
    به عنوان تابعی که قصد داریم روی دیتافریم اعمال کنیم، از <code>sum</code> که در نامپای وجود دارد استفاده کرده‌ایم.
</font>
</p>

In [5]:
df.drop(['sum'], axis=1, inplace=True)
df.apply(np.sum)

col_1     30
col_2    174
dtype: int64

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مثال سوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
   حال در مثال سوم می‌خواهیم همه المان‌های یک دیتافریم را بر ۲ تقسیم کنیم.
    <br>
    دیتافریم این مثال همان دیتافریم دو مثال قبلی است.
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
روش اول
</font>
</h3>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در روش اول می‌خواهیم به ترتیب سطرها تقسیم را انجام دهیم. یعنی ابتدا همه المان‌های سطر اول، سپس همه المان‌های سطر دوم و الی آخر را بر ۲ تقسیم کنیم.
    <br>
    به این منظور تابع <code>row_divide_2</code> را تعریف می‌کنیم با استفاده از <code>apply</code> آن را روی سطر‌های دیتافریم اعمال می‌کنیم.
</font>
</p>

In [6]:
def row_divide_2 (row) :
  return row / 2 
df.apply(row_divide_2, axis=1)

   col_1  col_2
0    0.5   12.5
1    2.0   18.0
2    4.5   24.5
3    8.0   32.0

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
روش دوم
</font>
</h3>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    این بار با تعریف تابع <code>col_divide_2</code> و اعمال ستون به ستون آن با استفاده از <code>apply</code> قصد داریم همه المان‌های دیتافریم را بر ۲ تقسیم کنیم.
</font>
</p>

In [7]:
def col_divide_2 (col) : 
    return col / 2 

df.apply(col_divide_2)

   col_1  col_2
0    0.5   12.5
1    2.0   18.0
2    4.5   24.5
3    8.0   32.0

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
روش سوم
</font>
</h3>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    راه حل خیلی ساده‌تری نسبت به <code>apply</code> هم وجود دارد!
</font>
</p>

In [8]:
df/2

   col_1  col_2
0    0.5   12.5
1    2.0   18.0
2    4.5   24.5
3    8.0   32.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    <code>sort_values</code> پارامترهای مهم تابع 
    </font>
</h2>

```python
DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort',na_position='last',\
                      ignore_index=False, key=None)
```

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=3>
        
| پارامتر| توضیحات|
| ------------ |-------- |
| by| می‌تواند اسم ستون یا نمایه سطر باشد. اگر بخواهیم چندین ستون یا چندین سطر را برای مرتب‌سازی در نظر بگیریم می‌توانیم لیست اسامی ستون‌ها را به این پارامتر پاس بدهیم.|
| axis| نوع مرتب‌سازی را مشخص می‌کند که بر اساس سطر باشد یا ستون.<br><br><br>- اگر 0 باشد مرتب‌سازی ستونی است.<br>- اگر 1 باشد مرتب‌سازی سطری است.|
| ascending| دو مقدار True یا False را می‌تواند داشته باشد.<br><br>- اگر False باشد مرتب‌سازی نزولی است. مقدار پیش‌فرض False است.<br>- اگر True باشد مرتب‌سازی صعودی است.|
| inplace| دو مقدار True یا False را می‌تواند داشته باشد.<br><br>- اگر مقدار این پارامتر True باشد، نتیجه مرتب‌سازی درون دیتا‌فریم اصلی کپی می‌شود.<br>- اگر False باشد یک نسخه مرتب‌شده از دیتافریم را return می‌کند.|
| kind| الگوریتم مرتب‌سازی را مشخص‌ می‌کند. به صورت پیش‌فرض روی quicksort تنظیم شده است.|
| na_position  | محل قرارگیری NaN (Not a Number) ها را در فریم مرتب‌شده مشخص می‌کند.<br><br>- اگر last باشد در آخرین سطر‌ها قرار می‌گیرند. پیش‌فرض این پارامتر last است.<br>- اگر first باشد در سطرهای ابتدایی قرار می‌گیرند.|
| ignore_index | چون ممکن است پس از مرتب‌سازی نمایه‌ها جابه‌جا شوند (مثلا نمایه 0 مربوط به اولین سطر نباشد)، می‌توانیم با این پارامتر نمایه‌ها را بازآرایی کنیم.<br><br>- اگر True باشد، نمایه سطرهای مرتب‌شده از 0 تا L -1 خواهد بود که L تعداد سطرهای آرایه‌است. <br>- اگر False باشد، هر سطر نمایه پیش از مرتب‌سازی را حفظ می‌کند. |
| key| تابعی که پیش از مرتب‌سازی، روی عناصر موجود در سطرها یا ستون‌هایی که در `by` وجود دارد، اعمال می‌شود. در مثال‌ها بیشتر با این کارکرد این پارامتر آشنا می‌شویم.|
        
<div>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مثال
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
 جدول اطلاعات دانشجویان را در اختیار داریم و می‌خواهیم آن را مرتب کنیم.
</font>
</p>

In [9]:
stu_dictionary = {
    "name" : ["PARTO", "parsa", "SAJJAD", "hadi", "MOHSEN", "ghazale", "hamed"] ,
    "stu_number" : ["963613060", "963613061", "963613062", "963613063", "963613064", "963613065", "933613080"] ,
    "average" : [19.68,19.90,17.27, 19.5, 15.9, 18.2, 19.34]
}
df = pd.DataFrame(stu_dictionary)
df

      name stu_number  average
0    PARTO  963613060    19.68
1    parsa  963613061    19.90
2   SAJJAD  963613062    17.27
3     hadi  963613063    19.50
4   MOHSEN  963613064    15.90
5  ghazale  963613065    18.20
6    hamed  933613080    19.34

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش اول
</font>
</h3>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
   در اولین قسمت می‌خواهیم دانشجویان را بر اساس معدل به ترتیب نزولی مرتب کنیم.
</font>
</p>

In [10]:
df.sort_values(by='average', ascending=False)

      name stu_number  average
1    parsa  963613061    19.90
0    PARTO  963613060    19.68
3     hadi  963613063    19.50
6    hamed  933613080    19.34
5  ghazale  963613065    18.20
2   SAJJAD  963613062    17.27
4   MOHSEN  963613064    15.90

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش دوم
</font>
</h3>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
   در قسمت دوم می‌خواهیم دانشجویان را بر اساس نام مرتب‌سازی کنیم.
</font>
</p>

In [11]:
df.sort_values('name')

      name stu_number  average
4   MOHSEN  963613064    15.90
0    PARTO  963613060    19.68
2   SAJJAD  963613062    17.27
5  ghazale  963613065    18.20
3     hadi  963613063    19.50
6    hamed  933613080    19.34
1    parsa  963613061    19.90

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    به جدول بالا دقت کنید. اسم PARTO و parsa تفاوت زیادی با هم دارند! ایرادات زیاد دیگری هم دارد.
    <br>
    ایراد آن است که برخی اسم‌ها به حروف بزرگ لاتین نوشته شده‌اند. این اتفاق نباید تاثیری در مرتب‌سازی داشته باشد.
    <br>
    راه حل این است که قبل از اعمال مرتب‌سازی، همه اسم‌ها را به حروف کوچک تبدیل کنیم. برای اینکار می‌توانیم در پارامتر <code>key</code> تابع <code>lower</code> را قرار دهیم.
</font>
</p>

In [12]:
df.sort_values(by='name', key=lambda name : name.str.lower())

      name stu_number  average
5  ghazale  963613065    18.20
3     hadi  963613063    19.50
6    hamed  933613080    19.34
4   MOHSEN  963613064    15.90
1    parsa  963613061    19.90
0    PARTO  963613060    19.68
2   SAJJAD  963613062    17.27

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در عبارت لامدایی که در پارامتر <code>key</code> نوشته شده است، به عنوان ورودی name را داده‌ایم و با گرفتن قسمت رشته‌ای آن، حروفش را کوچک کرده‌ایم.
</font>
</p>