In [10]:
import numpy as np
import pandas as pd
from scipy.stats import multinomial

In [2]:
df = pd.read_csv("data/scores.csv")
df.head()

      Status  Math  Physics  Literature
0  bookworms    85       73          39
1     gamers    58       55          47
2  bookworms    59       50          71
3  bookworms    39       52          93
4     gamers    51       77          73

In [3]:
df["avg"] = (df["Math"] + df["Physics"] + df["Literature"]) / 3
df.head()

      Status  Math  Physics  Literature        avg
0  bookworms    85       73          39  65.666667
1     gamers    58       55          47  53.333333
2  bookworms    59       50          71  60.000000
3  bookworms    39       52          93  61.333333
4     gamers    51       77          73  67.000000

In [4]:
def score_changer(score):
    if score >= 70:
        return "A"
    elif score >= 50:
        return "B"
    else:
        return "C"

In [5]:
df['FinalScore'] = df['avg'].apply(lambda x : score_changer(x))
df.head()

      Status  Math  Physics  Literature        avg FinalScore
0  bookworms    85       73          39  65.666667          B
1     gamers    58       55          47  53.333333          B
2  bookworms    59       50          71  60.000000          B
3  bookworms    39       52          93  61.333333          B
4     gamers    51       77          73  67.000000          B

In [6]:
joint_df = df.groupby(['Status','FinalScore']).size().unstack()/len(df)
joint_df

FinalScore      A      B      C
Status
bookworms   0.154  0.330  0.060
gamers      0.146  0.266  0.044

In [7]:
score_marginal_distribution = joint_df.sum(axis=0)

In [8]:
status_marginal_distribution = joint_df.sum(axis=1)

In [9]:
p_A_given_book = joint_df.loc['bookworms', 'A'] / status_marginal_distribution['bookworms']
p_A_given_gamer = joint_df.loc['gamers', 'A'] / status_marginal_distribution['gamers']
nerds_to_gamers = round(abs((p_A_given_book / p_A_given_gamer) - 1) * 100 , 2)
nerds_to_gamers

np.float64(11.58)

In [11]:
n = 1000
k = [400, 380 , 220]
p = [0.4 , 0.35 , 0.25]

prob = round(np.exp(multinomial.logpmf(k , n , p)), 6)

print(prob)

3.8e-05