In [27]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([12,13,14,8,9,20])
print(s)

0    12
1    13
2    14
3     8
4     9
5    20
dtype: int64

In [3]:
s = pd.Series([12,13,14,8,9,20], index = ['sara','omid','mohammad','reza','mina','nili'])
print(s)

sara        12
omid        13
mohammad    14
reza         8
mina         9
nili        20
dtype: int64

In [4]:
s = s.reindex( ['sara','omid','mohammad','mahan','mina','nili'])
print(s)

sara        12.0
omid        13.0
mohammad    14.0
mahan        NaN
mina         9.0
nili        20.0
dtype: float64

In [5]:
print(s[1])

13.0

C:\Users\ALFA\AppData\Local\Temp\ipykernel_23472\819424605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1])

In [6]:
print(s['omid'])

13.0

In [7]:
s['mahan'] = 20
print(s)

sara        12.0
omid        13.0
mohammad    14.0
mahan       20.0
mina         9.0
nili        20.0
dtype: float64

In [8]:
print(s.index)

Index(['sara', 'omid', 'mohammad', 'mahan', 'mina', 'nili'], dtype='object')

In [9]:
print(s[1:3])

omid        13.0
mohammad    14.0
dtype: float64

In [10]:
print(s[:2])

sara    12.0
omid    13.0
dtype: float64

In [11]:
print(s.iloc[:2])

sara    12.0
omid    13.0
dtype: float64

In [12]:
print(s.values)

[12. 13. 14. 20.  9. 20.]

In [13]:
print(s.index)

Index(['sara', 'omid', 'mohammad', 'mahan', 'mina', 'nili'], dtype='object')

In [15]:
s.index.name = 'name'
print(s)

name
sara        12.0
omid        13.0
mohammad    14.0
mahan       20.0
mina         9.0
nili        20.0
dtype: float64

In [16]:
s.name = 'score'
print(s)

name
sara        12.0
omid        13.0
mohammad    14.0
mahan       20.0
mina         9.0
nili        20.0
Name: score, dtype: float64

In [17]:
s = s.drop('omid')
print(s)

name
sara        12.0
mohammad    14.0
mahan       20.0
mina         9.0
nili        20.0
Name: score, dtype: float64

In [18]:
myseries = pd.Series([14,15,16,17,18],index=['araz','ali','samin','celin','fatemeh'])
print(myseries)

araz       14
ali        15
samin      16
celin      17
fatemeh    18
dtype: int64

In [19]:
print(myseries.pop('celin'))
print(myseries)

17
araz       14
ali        15
samin      16
fatemeh    18
dtype: int64

In [20]:
h = ('AA','2023-04-31',100,10,10.2)
S = pd.Series(h)
type(S)

pandas.core.series.Series

In [21]:
print(S)

0            AA
1    2023-04-31
2           100
3            10
4          10.2
dtype: object

In [22]:
d = {'name':'IBM', 'date':'2023-04-05', 'shares':100, 'price':10.2}
ds = pd.Series(d)

In [23]:
type(ds)

pandas.core.series.Series

In [24]:
print(ds)

name             IBM
date      2023-04-05
shares           100
price           10.2
dtype: object

In [25]:
ds['shares']

100

In [26]:
ds[0]

C:\Users\ALFA\AppData\Local\Temp\ipykernel_23472\3903559858.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ds[0]

'IBM'

In [28]:
s = pd.Series([12,4,5,np.nan,7,2],index=['a','b','c','d','e','f'])
print(s)

a    12.0
b     4.0
c     5.0
d     NaN
e     7.0
f     2.0
dtype: float64

In [29]:
print(s.isna())

a    False
b    False
c    False
d     True
e    False
f    False
dtype: bool

In [30]:
print(s.notna())

a     True
b     True
c     True
d    False
e     True
f     True
dtype: bool

In [31]:
print(s.isin([5]))

a    False
b    False
c     True
d    False
e    False
f    False
dtype: bool

In [32]:
s1 = s.copy()

In [33]:
s['b'] = 89
print(s)

a    12.0
b    89.0
c     5.0
d     NaN
e     7.0
f     2.0
dtype: float64

In [34]:
print(s.sort_index)

<bound method Series.sort_index of a    12.0
b    89.0
c     5.0
d     NaN
e     7.0
f     2.0
dtype: float64>

In [35]:
print(s.sort_values())

f     2.0
c     5.0
e     7.0
a    12.0
b    89.0
d     NaN
dtype: float64

In [36]:
print(s.rank())

a    4.0
b    5.0
c    2.0
d    NaN
e    3.0
f    1.0
dtype: float64

In [37]:
print(s['b'])

89.0

In [38]:
s = pd.Series([12,4,5,np.nan,7,2],index=['a','b','c','a','b','d'])
print(s)

a    12.0
b     4.0
c     5.0
a     NaN
b     7.0
d     2.0
dtype: float64

In [39]:
print(s.index.is_unique)

False

In [40]:
print(s.describe())

count     5.000000
mean      6.000000
std       3.807887
min       2.000000
25%       4.000000
50%       5.000000
75%       7.000000
max      12.000000
dtype: float64

In [41]:
print(s.count())

5

In [42]:
print(s>5)

a     True
b    False
c    False
a    False
b     True
d    False
dtype: bool

In [43]:
data = {'name':['aa','ibm','goog'],
        'date' : ['2001-12-01','2012-02-01','2010-04-09'],
        'shares' : [100,200,30],
        'price' : [12.3,10.3,32.2]
        }

In [44]:
df = pd.DataFrame(data)
type(df)

pandas.core.frame.DataFrame

In [ ]:
df

   name        date  shares  price
0    aa  2001-12-01     100   12.3
1   ibm  2012-02-01     200   10.3
2  goog  2010-04-09      30   32.2

In [46]:
df['owner'] = 'unknown'
df

   name        date  shares  price    owner
0    aa  2001-12-01     100   12.3  unknown
1   ibm  2012-02-01     200   10.3  unknown
2  goog  2010-04-09      30   32.2  unknown

In [47]:
df.index = ['one','two','three']
df

       name        date  shares  price    owner
one      aa  2001-12-01     100   12.3  unknown
two     ibm  2012-02-01     200   10.3  unknown
three  goog  2010-04-09      30   32.2  unknown

In [48]:
df = df.set_index(['name'])
df

            date  shares  price    owner
name
aa    2001-12-01     100   12.3  unknown
ibm   2012-02-01     200   10.3  unknown
goog  2010-04-09      30   32.2  unknown

In [49]:
df['shares']

name
aa      100
ibm     200
goog     30
Name: shares, dtype: int64

In [50]:
del df['owner']
df

            date  shares  price
name
aa    2001-12-01     100   12.3
ibm   2012-02-01     200   10.3
goog  2010-04-09      30   32.2

In [51]:
df.drop('shares',axis=0)

KeyError: "['shares'] not found in axis"

In [54]:
len(df)

3

In [55]:
df.head(3)

            date  shares  price
name
aa    2001-12-01     100   12.3
ibm   2012-02-01     200   10.3
goog  2010-04-09      30   32.2

In [56]:
t = df['shares']
type(t)

pandas.core.series.Series

In [57]:
t.head()

name
aa      100
ibm     200
goog     30
Name: shares, dtype: int64